### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Test4QDS001)
add_subdirectory(Test4QDS001Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Test4QDS001plugin
    Test4QDS001Contentplugin
    QtQuickDesignerComponents)